export interface KeyFunction {
  id: string;
  name: string;
  description: string;
  priority: "High" | "Medium" | "Low";
}

export interface SystemSoftware {
  id: string;
  name: string;
  purpose: string;
  accessProvidedBy: "Client" | "CC" | "RP already has access";
  loginDetailsReady: "Yes" | "No" | "N/A";
}

export interface KPI {
  id: string;
  functionId: string;
  name: string;
  targetValue: string;
  measurementMethod: string;
  thirtyDayTarget: string;
  ninetyDayTarget: string;
}

export interface TrainingResource {
  id: string;
  name: string;
  type: "Loom" | "Scribe" | "Document" | "Video" | "Live Training";
  url: string;
  status: "Ready" | "To be created" | "N/A";
}

export interface IntegrationQuestionnaire {
  // Step 1: Client & Role Details
  clientName: string;
  clientContactName: string;
  clientContactEmail: string;
  rpName: string;
  roleTitle: string;
  startDate: string;
  workingHoursStart: string;
  workingHoursEnd: string;
  workingDays: string[];
  timezone: string;

  // Step 2: Position Description & Functions
  positionDescription: string;
  keyFunctions: KeyFunction[];

  // Step 3: Systems & Software
  systems: SystemSoftware[];

  // Step 4: KPIs & Performance Expectations
  kpis: KPI[];

  // Step 5: Training & Resources
  primaryTrainer: string;
  trainingResources: TrainingResource[];
  primaryChannel: "Teams" | "Slack" | "Email" | "WhatsApp";
  escalationContactName: string;
  escalationContactEmail: string;
}

export const TIMEZONES = [
  "AEST (UTC+10)",
  "AEDT (UTC+11)",
  "ACST (UTC+9:30)",
  "ACDT (UTC+10:30)",
  "AWST (UTC+8)",
  "NZST (UTC+12)",
  "NZDT (UTC+13)",
  "PHT (UTC+8)",
  "SGT (UTC+8)",
  "IST (UTC+5:30)",
] as const;

export const WORKING_DAYS = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
] as const;

export function generateTimeSlots(): string[] {
  const slots: string[] = [];
  for (let h = 0; h < 24; h++) {
    for (let m = 0; m < 60; m += 15) {
      const hour = h.toString().padStart(2, "0");
      const min = m.toString().padStart(2, "0");
      slots.push(`${hour}:${min}`);
    }
  }
  return slots;
}

export function createEmptyQuestionnaire(): IntegrationQuestionnaire {
  return {
    clientName: "",
    clientContactName: "",
    clientContactEmail: "",
    rpName: "",
    roleTitle: "",
    startDate: "",
    workingHoursStart: "08:00",
    workingHoursEnd: "17:00",
    workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    timezone: "AEST (UTC+10)",
    positionDescription: "",
    keyFunctions: [],
    systems: [],
    kpis: [],
    primaryTrainer: "",
    trainingResources: [],
    primaryChannel: "Teams",
    escalationContactName: "",
    escalationContactEmail: "",
  };
}

// --- Onboarding Program types (generated by Claude API) ---

export interface OnboardingTask {
  id: string;
  functionName: string;
  taskName: string;
  description: string;
  greenCriteria: string;
  priority: "High" | "Medium" | "Low";
  targetWeek: number;
  trainingMethod: string;
  estimatedHours: number;
}

export interface WeekPlan {
  weekNumber: number;
  focus: string;
  tasks: string[];
  checkInAgenda: string[];
}

export interface OnboardingProgram {
  rpName: string;
  roleTitle: string;
  clientName: string;
  startDate: string;
  totalTasks: number;
  tasks: OnboardingTask[];
  weeklyPlan: WeekPlan[];
  dayOneChecklist: string[];
  systemAccessChecklist: { system: string; status: string }[];
}

let _idCounter = 0;
export function generateId(): string {
  _idCounter++;
  return `${Date.now()}-${_idCounter}`;
}
